#############################################
# diffusion-transformer-image.yaml
# Configuration for diffusion-based transformer policy (image-based)
#############################################

extends: ./common.yaml

model:
  name: diffusion-transformer-image    # diffusion transformer for image observations
  horizon: 16                          # temporal horizon
  n_obs_steps: 2                       # observation frames fed in
  n_action_steps: 8                    # number of future action steps to output
  num_inference_steps: 100             # diffusion sampling steps
  
  # Image processing
  crop_shape: [76, 76]
  obs_encoder_group_norm: false
  eval_fixed_crop: false
  visual_encoder: "ResNet18Conv"
  
  # Transformer architecture
  transformer:
    n_layer: 8
    n_head: 4  
    n_emb: 256
    p_drop_emb: 0.0
    p_drop_attn: 0.3
    causal_attn: true